language: node_js
node_js: stable
env:
  global:
  - GH_REF: github.com/mauriciosantos/Buckets-JS.git
  - secure: QfIjKGlZ7cvDZSITpr8q72+tGdYa1uSb3HwTprM1orhNbrYSAt1+fnXppMLxeTL6mgk7VTnokMJ/WRLHgrsfqaIPQ0ic9NapDE0fId0b6whG4iCJy1iDDm0vmdiGEQeVIXd+cJ700mYuxeBgSdQvr4roBHeoXWmRH7zot0mVM/pAa/fG7gVGGJ5EC8gVmtoMBFxHBDSu+HKXRbiwBRA3un3D/tf3hs2l3frwUmy5fBllAi3fe2ruQ4uQjLIOcn/l7S2HvAIRcjLr+Nxtvz7jRZqi/fY4FuLNG8dPqR9lxIRqkYZYj5EJij1ssfiNZpMEZwfF033wxRPV6q4cdau9gw2EGtF5GUksLQXJyWzij+hox5Gfyy9oiMRI9vS9l1uiOT+x09TKsFoPRkIQG89e+JLSKLinqK4niHRpnNCJfDiENLPa50Ulf8DA9esG5SHuorh5J9zsjLc2Gm5sp8E43Oz/gskGZcSLGswjuKO/jxQ0LmKSqeQAbiB4sVN9IyeNJGZDzK5qCooy5jUmRG4MrY8cKqAvOivsvXNdvxt7q3sadb+kLGJy/AWZUg442muFEv0yOyyrSqUElriQGJ44ejKkh6SgXN8qz1mayMPPJYG9fbC7YC3/3x6iRQkxO3u+5CeoKfab8I6XqqwEcNCr3+IYlaGCnO4VPhbvvDeOgv4=
before_install: npm install -g grunt-cli
before_script: grunt test && grunt build # Test dist files before and after build
after_success: grunt publish-docs
before_deploy: git reset --hard HEAD # Clean generated files to publish to NPM
deploy:
- provider: npm
  email:
    secure: byaTRGJFkYC9hbe7NPN++JQy/1e7QfBD+Aw6YgysbvhEnBL+QlKwMuJCcCqoEtcyHv4HdR8Otl999KNeLz0ygGtlZ9H2aDksmKcj+bOpLb7c5eLZ5sl+3/d+cXobJvHLfiGzoyNEBsus0gn7CozTLeZ/KVaVdgUd8SW8GOMezfhQsL25zxONdWba2z9zHOlKjtJoLjtQXLYpTBTj9Stuw06BSBmaJbXwNDFhhQ2ae+GLG0bVP6GR10MkHt/iBPR2HuktN1dk3/OQZTd1jXceKQdK+0oMSLWWo2gXmaX5p3Co2lRZ48pXaAu7XI2PCuM/M0qPn+NsFTASVQ5DlF5h97mNUIZbafk+MIYI+azNW5/sqr40FTrynWBRN+lMttpYC0toVg5kJ9CU8FBBmJeDmVgt7A2TOm2tqqpc5izAKnfSLIpPcgJUsAh7xqoQRDBTujwIA/ww2DRCYozKxvOwIOfURrIjicHk/ghPf84iRSqb1GOQzO97R1iJ6Jv5YkOasjnrobOnQLFrcH9m3issDq5kLBZo1J+zqLBFy8Vx49YYO4zXAUJOimxhuiALuXA2s/ipV3SNEwJcIcsEswWGZLpZ1LM/PnwKmLWl0Yjz8O3Ik57FLVWXBy1ShJpRqrMpmGuRLb0X1hivlXGSJNJJ2uzg8QPSPC7NHi59N6h8zUg=
  api_key:
    secure: qnqMejCpkMqpVRPbKODsTfnZmCxgbFk/XWoix50nAB8cgIp+mAatHNaLrysWggebn2709M/pN4hioQKxCm9JC3kzidg7LyZlyvRyBBLmydvz3yyB62ZFLx78EIeoV6mJCKNRoW+G5hXI6ist1m5hPuTnXWiPvp4Hr7u/LX+FC/xObrFuMYleQ0njMBs+id0UEiTO3nbL/0Dy7r93zcUUxUQFUy5Si9mX0+X7MqcIke0kJHFmDtMdYIWaV155oyvWqYH9uC52eCzPRKGTyrelq64gKB6E3L91DdiJtLWbOtZ4rH+Yl3i+fKUFtqkeyHSzFcwilpJlz+RoG/IUNO99kBP++DyAT1FpRzueAzpFSg1MCSf3TBJbbutpKhy2kSavt0vxVYgVx7hECVp3zcUIJ7vnWjwhZwIIQNX5Lybsd4JRo0mipRH/RyuoGkSS7+E+XxyskmHHNmMxNwvjSudzjLto2IZy4rWLc8NfwtDc5J/sgjomGl6VS2uN6yjMlVPIPzmj/DyQjoR0mgW3CVOZ320qzPjh9KLm9NQq8vasKUKUV3Tnt10HL6FVzy7JD+JORqKqV0UBo/pfnKg/zhWIx4DCqGAV462A3fMj4bsdyAP0YXBqAB3wUauOJWrCP+01L5WonoSVQpWPbogqPQf9qSXgP3jbo88eepwSSDd6SIQ=
  on:
    tags: true
    repo: mauriciosantos/Buckets-JS
- provider: releases
  api_key:
    secure: cRXlKAtpDxBXf5IbkdzviQzdS9A1K8i0JgB0VSUSlIPjbaLGGUH0yqi1Jjl8zOn2uBJZmkYOMWFfR54dlXIakmoDkJadloaHdplaannOIDUwdn6LfaPqB6XGMIxe+NIZZVWLpvcjhaWnoJPnJZIUPgVS7bCx35WkGn3xCxcVjuDO4glVDrUb7ZnDAim48Pn2UJOzDEiYFuj+fsu9svV5TSC1fQEVtjG49q2VDNzuAtCWukBJKQ1jscws1q/1AeLHQgeBPXiGWUfhpRpiqaUA4pXKmfWe5/hpprOdzMi82DTPx5GuHXnw2/d/U52DEi4gfQyd3LKlKVuxkASXDgIsPpr9JMUD1KHpGTpFYOGGYs6qxBqdlal/3Sy8nCNphKRk+e4aRMdXnMDyQkFOOOlOPkuDfHjFjdKcjQj3lwez0GKbkK8j5SNEgXdoDxyv1xJkv2QGkv3+OztWp6JFb9idGJ9xjADwpX2TGHP70Focx5nnGM93azqTUU3nH7eMJdMRjoOqGopqXuXt6bub3jttmosyclF3zk5b8VpGpt3/71sNAURop/F96n3t5Yd0paoDF2TYR6z+qNRFOjzjYfoVNkaJRoY96w7WTxbcZnAQTKjooophN/Nc8/8VodKNhqE8LXmzRvHhkigxA5xXJUgj3ilQOVca0mKfpd6xRFcjW20=
  file:
    - "dist/buckets.js"
    - "dist/buckets.min.js"
    - "dist/buckets.min.js.map"
  on:
    tags: true
    repo: mauriciosantos/Buckets-JS
